import prisma from '../src/lib/prisma';

type QuestionSeed = {
  prompt: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  topics: string[];
};

const questions: QuestionSeed[] = [
  {
    prompt: 'What is the primary purpose of a load balancer?',
    options: ['Store application data', 'Distribute incoming requests across multiple servers', 'Encrypt network traffic', 'Monitor application logs'],
    correctAnswer: 'Distribute incoming requests across multiple servers',
    explanation: 'A load balancer distributes incoming requests across multiple servers to improve availability and prevent one server from becoming overloaded.',
    difficulty: 'easy',
    topics: ['scalability', 'load-balancing'],
  },
  {
    prompt: 'Which caching strategy helps reduce database load by storing frequently accessed data?',
    options: ['Replication', 'Sharding', 'In-memory cache', 'Compression'],
    correctAnswer: 'In-memory cache',
    explanation: 'An in-memory cache stores frequently accessed data in fast memory so the application does not need to repeatedly query the database.',
    difficulty: 'easy',
    topics: ['caching', 'databases', 'scalability'],
  },
  {
    prompt: 'Which database property ensures data remains accurate and valid after a transaction?',
    options: ['Durability', 'Consistency', 'Availability', 'Replication'],
    correctAnswer: 'Consistency',
    explanation: 'Consistency ensures that a transaction moves the database from one valid state to another while preserving rules and constraints.',
    difficulty: 'easy',
    topics: ['databases', 'consistency'],
  },
  {
    prompt: 'What is the main purpose of a Content Delivery Network (CDN)?',
    options: ['Manage authentication', 'Store relational data', 'Deliver content closer to users', 'Process background jobs'],
    correctAnswer: 'Deliver content closer to users',
    explanation: 'A CDN serves static or cacheable content from edge locations closer to users, reducing latency and improving performance.',
    difficulty: 'easy',
    topics: ['networking', 'caching', 'scalability'],
  },
  {
    prompt: 'Which protocol is most commonly used for web APIs?',
    options: ['FTP', 'SMTP', 'HTTP', 'SSH'],
    correctAnswer: 'HTTP',
    explanation: 'HTTP is the most common protocol for web APIs because it supports request-response communication over the web.',
    difficulty: 'easy',
    topics: ['api-design', 'networking'],
  },
  {
    prompt: 'What is horizontal scaling?',
    options: ['Adding memory to a server', 'Adding CPU cores to a server', 'Adding more servers', 'Migrating to the cloud'],
    correctAnswer: 'Adding more servers',
    explanation: 'Horizontal scaling means adding more machines or instances to handle increased load.',
    difficulty: 'easy',
    topics: ['scalability'],
  },
  {
    prompt: 'What is the primary purpose of a message queue?',
    options: ['Store images permanently', 'Decouple services and process tasks asynchronously', 'Secure API endpoints', 'Manage DNS records'],
    correctAnswer: 'Decouple services and process tasks asynchronously',
    explanation: 'A message queue lets producers and consumers communicate asynchronously, which decouples services and improves resilience under load.',
    difficulty: 'easy',
    topics: ['message-queues', 'reliability', 'microservices'],
  },
  {
    prompt: 'Which storage type is best suited for large media files?',
    options: ['Object storage', 'Cache storage', 'Session storage', 'Memory storage'],
    correctAnswer: 'Object storage',
    explanation: 'Object storage is well suited for large unstructured files such as images, videos, and backups.',
    difficulty: 'easy',
    topics: ['storage-systems'],
  },
  {
    prompt: 'What does replication improve in a database system?',
    options: ['Read availability', 'Query syntax', 'Authentication', 'API versioning'],
    correctAnswer: 'Read availability',
    explanation: 'Replication can improve read availability by allowing reads from multiple database copies.',
    difficulty: 'easy',
    topics: ['databases', 'reliability'],
  },
  {
    prompt: 'What is the primary purpose of monitoring in a distributed system?',
    options: ['Increase disk space', 'Track system health and performance', 'Encrypt user data', 'Balance network traffic'],
    correctAnswer: 'Track system health and performance',
    explanation: 'Monitoring tracks metrics, logs, and system behavior so teams can detect issues and understand performance.',
    difficulty: 'easy',
    topics: ['observability', 'reliability'],
  },
  {
    prompt: 'A news website experiences heavy read traffic but relatively few writes. Which approach is most appropriate?',
    options: ['Add a caching layer', 'Increase password complexity', 'Use message queues only', 'Remove database indexes'],
    correctAnswer: 'Add a caching layer',
    explanation: 'A caching layer serves repeated reads from cache, reducing database load and improving latency.',
    difficulty: 'medium',
    topics: ['caching', 'scalability', 'databases'],
  },
  {
    prompt: 'A system stores billions of user records and a single database server is becoming a bottleneck. What is a common scaling strategy?',
    options: ['Sharding', 'Compression', 'Logging', 'Authentication'],
    correctAnswer: 'Sharding',
    explanation: 'Sharding splits data across multiple database partitions or nodes, allowing the system to scale beyond one server.',
    difficulty: 'medium',
    topics: ['databases', 'scalability'],
  },
  {
    prompt: 'A photo-sharing application generates image thumbnails after uploads. Which component is best suited for handling thumbnail generation?',
    options: ['CDN', 'Message queue with worker service', 'DNS server', 'Browser cache'],
    correctAnswer: 'Message queue with worker service',
    explanation: 'A message queue with worker services allows thumbnail generation to happen asynchronously after the upload.',
    difficulty: 'medium',
    topics: ['message-queues', 'storage-systems', 'microservices'],
  },
  {
    prompt: 'Which API design practice improves backward compatibility?',
    options: ['Frequent breaking changes', 'API versioning', 'Removing deprecated fields immediately', 'Disabling documentation'],
    correctAnswer: 'API versioning',
    explanation: 'API versioning lets clients continue using older API contracts while newer versions evolve.',
    difficulty: 'medium',
    topics: ['api-design'],
  },
  {
    prompt: 'A service depends on another service that occasionally becomes unavailable. Which strategy helps prevent cascading failures?',
    options: ['Circuit breaker', 'Replication', 'Sharding', 'Normalization'],
    correctAnswer: 'Circuit breaker',
    explanation: 'A circuit breaker stops repeated calls to an unhealthy dependency, preventing failures from spreading.',
    difficulty: 'medium',
    topics: ['reliability', 'microservices'],
  },
  {
    prompt: 'Why would a company use read replicas?',
    options: ['To improve write speed', 'To distribute read traffic', 'To replace API gateways', 'To reduce network latency'],
    correctAnswer: 'To distribute read traffic',
    explanation: 'Read replicas handle read queries separately, reducing load on the primary database.',
    difficulty: 'medium',
    topics: ['databases', 'scalability', 'reliability'],
  },
  {
    prompt: 'A chat application requires near real-time message delivery. Which communication approach is most suitable?',
    options: ['Batch processing', 'WebSockets', 'Email', 'FTP'],
    correctAnswer: 'WebSockets',
    explanation: 'WebSockets support persistent, bidirectional communication, making them suitable for near real-time chat.',
    difficulty: 'medium',
    topics: ['networking', 'api-design'],
  },
  {
    prompt: 'Which metric is most useful for measuring API responsiveness?',
    options: ['Disk size', 'Latency', 'CPU model', 'Number of developers'],
    correctAnswer: 'Latency',
    explanation: 'Latency measures how long it takes for an API to respond, making it directly relevant to responsiveness.',
    difficulty: 'medium',
    topics: ['observability', 'api-design'],
  },
  {
    prompt: 'A microservices architecture often uses an API gateway primarily to:',
    options: ['Replace databases', 'Provide a unified entry point', 'Store user sessions permanently', 'Execute background jobs'],
    correctAnswer: 'Provide a unified entry point',
    explanation: 'An API gateway provides a single entry point for clients and routes requests to internal services.',
    difficulty: 'medium',
    topics: ['microservices', 'api-design'],
  },
  {
    prompt: 'Which database indexing benefit is most accurate?',
    options: ['Faster query performance', 'Reduced API latency only', 'Stronger authentication', 'Better replication consistency'],
    correctAnswer: 'Faster query performance',
    explanation: 'Indexes help the database locate matching rows more efficiently, improving query performance.',
    difficulty: 'medium',
    topics: ['databases'],
  },
  {
    prompt: 'A globally distributed application must remain available even during network partitions. According to the CAP theorem, which trade-off is typically required?',
    options: ['Sacrifice availability', 'Sacrifice partition tolerance', 'Sacrifice some consistency', 'Sacrifice durability'],
    correctAnswer: 'Sacrifice some consistency',
    explanation: 'During a network partition, a system that prioritizes availability often accepts weaker or eventual consistency.',
    difficulty: 'hard',
    topics: ['cap-theorem', 'consistency', 'distributed-systems'],
  },
  {
    prompt: 'An e-commerce platform uses asynchronous inventory updates. What is a likely consequence?',
    options: ['Strong consistency', 'Eventual consistency', 'Synchronous replication', 'Immediate global updates'],
    correctAnswer: 'Eventual consistency',
    explanation: 'Asynchronous updates can temporarily leave different parts of the system with different inventory values until updates propagate.',
    difficulty: 'hard',
    topics: ['consistency', 'distributed-systems', 'message-queues'],
  },
  {
    prompt: 'A database shard becomes overloaded while others are underutilized. What issue does this indicate?',
    options: ['Cache invalidation', 'Hot partition', 'API throttling', 'DNS propagation'],
    correctAnswer: 'Hot partition',
    explanation: 'A hot partition occurs when traffic or data is unevenly distributed and one shard receives much more load than others.',
    difficulty: 'hard',
    topics: ['databases', 'scalability', 'distributed-systems'],
  },
  {
    prompt: 'A distributed system uses leader-follower replication. What risk exists if the leader fails unexpectedly?',
    options: ['No impact', 'Temporary unavailability during leader election', 'CDN cache loss', 'DNS conflict'],
    correctAnswer: 'Temporary unavailability during leader election',
    explanation: 'If the leader fails, the system may need to elect a new leader before writes can continue, causing temporary unavailability.',
    difficulty: 'hard',
    topics: ['distributed-systems', 'reliability', 'databases'],
  },
  {
    prompt: 'A team needs exactly-once processing semantics for financial transactions. Which approach is most appropriate?',
    options: ['Ignore duplicate messages', 'Use idempotency and transaction guarantees', 'Increase cache size', 'Disable retries'],
    correctAnswer: 'Use idempotency and transaction guarantees',
    explanation: 'Idempotency prevents repeated requests from applying duplicate effects, while transaction guarantees help maintain correctness.',
    difficulty: 'hard',
    topics: ['reliability', 'message-queues', 'consistency'],
  },
  {
    prompt: 'A service receives traffic spikes 100x larger than normal. Which combination is most effective?',
    options: ['Auto-scaling and load balancing', 'DNS and compression', 'Database normalization only', 'API versioning'],
    correctAnswer: 'Auto-scaling and load balancing',
    explanation: 'Auto-scaling adds capacity as demand increases, while load balancing distributes traffic across available instances.',
    difficulty: 'hard',
    topics: ['scalability', 'load-balancing', 'reliability'],
  },
  {
    prompt: 'A distributed cache loses several nodes. What is a key design consideration to minimize impact?',
    options: ['Consistent hashing', 'SQL indexing', 'API documentation', 'Database normalization'],
    correctAnswer: 'Consistent hashing',
    explanation: 'Consistent hashing reduces key redistribution when cache nodes are added or removed.',
    difficulty: 'hard',
    topics: ['caching', 'distributed-systems', 'scalability'],
  },
  {
    prompt: 'During a network partition, two database replicas accept writes independently. What challenge occurs when connectivity is restored?',
    options: ['Log aggregation', 'Conflict resolution', 'API routing', 'CDN expiration'],
    correctAnswer: 'Conflict resolution',
    explanation: 'If replicas accept independent writes during a partition, the system must reconcile conflicting updates when communication is restored.',
    difficulty: 'hard',
    topics: ['consistency', 'distributed-systems', 'databases'],
  },
  {
    prompt: 'A recommendation system processes millions of user activity events per minute. Which architecture best supports scalability?',
    options: ['Single monolithic service', 'Message queue with distributed consumers', 'Browser local storage', 'Shared spreadsheet'],
    correctAnswer: 'Message queue with distributed consumers',
    explanation: 'A message queue with distributed consumers handles high event volume by spreading processing across multiple workers.',
    difficulty: 'hard',
    topics: ['message-queues', 'scalability', 'distributed-systems'],
  },
  {
    prompt: 'A system prioritizes availability over strict consistency. Which outcome is most likely?',
    options: ['Users may temporarily see stale data', 'All reads are strongly consistent', 'No network partitions occur', 'Transactions become faster due to normalization'],
    correctAnswer: 'Users may temporarily see stale data',
    explanation: 'Systems that prioritize availability may serve stale or eventually consistent data so they can continue responding during failures or delays.',
    difficulty: 'hard',
    topics: ['consistency', 'availability', 'distributed-systems'],
  },
];

for (const question of questions) {
  await prisma.question.upsert({
    where: { prompt: question.prompt },
    update: question,
    create: question,
  });
}

console.log(`Seeded ${questions.length} questions`);
await prisma.$disconnect();
